version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  convert-Untitled: 
      executor: python/default
    steps:
      - checkout
      - restore_cache: 
          key: dependencies     
      - python/install-deps
      -save_cache:
          key: dependencies
          paths:
            - "venv"
      - run: echo 'export 
      PATH=/home/circleci/.local/lib/python3.8/site-packages:$PATH' >> $BASH_ENV
      - run:
          name: Jupyter get HTML
          command: 
            jupyter nbconvert -execute -to html Untitled.ipynb 
      - store_artifacts: 
          path: ./Untitled.html
          
  workflows:
  main:
    jobs:
      - convert-Untitled
